### ISSUE TITLE
Doesn't work for all browsers

### ISSUE THREAD

**Issue by ic-768** [Aliqyan-21/wit.nvim#1]
Very useful plugin, thanks for sharing!

```
return {
	"aliqyan-21/wit.nvim",
	config = function()
		require("wit").setup({ search_engine = "duckduckgo" })
	end,
}
```

I unfortunately can't use this with duckduck go, as searching for e.g. `wit.nvim`, gives the following url:

`https://duckduckgo.com/search?q="wit.nvim"`

whereas duckduckgo searches have the format
`https://duckduckgo.com/?q=wit.nvim`

Also, for brave search:

`https://search.brave.com/search?q=wit.nvim`
You'll notice there's no `www` suffix, meaning we can't use this engine either as `www.` is hardcoded when constructing the url

**Comment by Aliqyan-21** [comment]
Hey thank you for this issue, you are right, my mistake I didn't tested it with duckduckgo

I think we can solve it though, there are many approaches but I think of this one:

###### We can do something like, predefine some famous search search engine urls for user friendliness (just like put the name of that engine in the config) and then for flexibility we can put the option of directly putting our preffered search engine url whichever we want to use...so like for famous search engines we have directly included the search engine in the table and for non-famous ones u can just include the url for that and the rest will be done...

For example:

```lua
return {
	"aliqyan-21/wit.nvim",
	config = function()
		require("wit").setup({ search_engine = "https://any_search_engine.com/search?q=" })
	end,
}
```

and for famous search engines we can define a table:

```lua
local search_engines = {
    google = "https://www.google.com/search?q=",
    bing = "https://www.bing.com/search?q=",
    duckduckgo = "https://duckduckgo.com/?q=",
    ecosia = "https://www.ecosia.org/search?q=",
    brave = "https://search.brave.com/search?q="
}
```

How about this?

**Comment by ic-768** [comment]
Yeah I think your approach should be good!

**Comment by Aliqyan-21** [comment]
You know it is good I think it is definitely...now people can include any search engine they want as long as they know it's url and as programmers they will definitely find it out and not only that...
Now you can search things directly in perplexity.ai too (as now we have table of search engines so we can define any urls and I have put perplexity in the supported search engines list too because why not) and any AI based search engine as long as there is a URL, I am testing it more and then I will push the commit. And then you too test it, I will really appreciate it Thank you for this!
